require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  CountAsOne: [array,hash]

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

Style/Documentation:
  AllowedConstants: [Fea]

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
